-- REINOS ONÍRICOS · FASE 5.5
-- SQL consolidada, segura para executar uma vez no SQL Editor do Supabase.
-- Não remove tabelas, não apaga dados e não habilita Realtime.

create extension if not exists pgcrypto;
create table if not exists public.profiles (user_id uuid primary key references auth.users(id) on delete cascade, nome text not null default 'Desvelado', avatar_url text, criado_em timestamptz not null default now(), atualizado_em timestamptz not null default now());
alter table public.profiles add column if not exists avatar_url text;
alter table public.profiles add column if not exists atualizado_em timestamptz not null default now();
create unique index if not exists profiles_user_id_unique on public.profiles(user_id);
create or replace function public.set_updated_at() returns trigger language plpgsql set search_path=public as $$ begin new.atualizado_em=now(); return new; end; $$;
drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at before update on public.profiles for each row execute function public.set_updated_at();
create or replace function public.create_profile_for_auth_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(user_id,nome) values(new.id,coalesce(new.raw_user_meta_data->>'nome',split_part(coalesce(new.email,'Desvelado'),'@',1))) on conflict(user_id) do nothing; return new; end; $$;
drop trigger if exists auth_user_profile_created on auth.users;
create trigger auth_user_profile_created after insert on auth.users for each row execute function public.create_profile_for_auth_user();

create table if not exists public.campaigns (id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id) on delete restrict, nome text not null, descricao text not null default '', imagem_url text, tipo text not null default 'campanha' check(tipo in ('campanha','oneshot','playtest')), status text not null default 'planejamento' check(status in ('em_andamento','planejamento','concluida')), codigo_convite text, ruptura_geral integer not null default 0 check(ruptura_geral between 0 and 6), sessao_atual integer not null default 1 check(sessao_atual>0), criado_em timestamptz not null default now(), atualizado_em timestamptz not null default now());
alter table public.campaigns add column if not exists codigo_convite text;
create unique index if not exists campaigns_invite_code_unique on public.campaigns(codigo_convite) where codigo_convite is not null;
create index if not exists campaigns_owner_idx on public.campaigns(owner_id);
drop trigger if exists campaigns_set_updated_at on public.campaigns;
create trigger campaigns_set_updated_at before update on public.campaigns for each row execute function public.set_updated_at();
create or replace function public.generate_invite_code() returns text language plpgsql volatile set search_path=public as $$ declare code text; begin loop code:='REINO-'||upper(substr(encode(gen_random_bytes(8),'hex'),1,12)); exit when not exists(select 1 from public.campaigns where codigo_convite=code); end loop; return code; end; $$;
update public.campaigns set codigo_convite=public.generate_invite_code() where codigo_convite is null;
create table if not exists public.campaign_members (campaign_id uuid not null references public.campaigns(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, role text not null check(role in ('mestre','jogador','observador')), character_id text, status text not null default 'ativo' check(status in ('ativo','pendente','removido')), joined_at timestamptz not null default now(), primary key(campaign_id,user_id));
create index if not exists campaign_members_user_idx on public.campaign_members(user_id,campaign_id);
create index if not exists campaign_members_character_idx on public.campaign_members(character_id) where character_id is not null;
create or replace function public.is_campaign_member(p_campaign_id uuid) returns boolean language sql security definer stable set search_path=public as $$ select exists(select 1 from public.campaign_members where campaign_id=p_campaign_id and user_id=auth.uid() and status='ativo'); $$;
create or replace function public.is_campaign_master(p_campaign_id uuid) returns boolean language sql security definer stable set search_path=public as $$ select exists(select 1 from public.campaign_members where campaign_id=p_campaign_id and user_id=auth.uid() and role='mestre' and status='ativo'); $$;
create or replace function public.create_campaign(p_nome text,p_descricao text default '',p_imagem_url text default '',p_tipo text default 'campanha') returns uuid language plpgsql security definer set search_path=public as $$ declare new_id uuid; begin if auth.uid() is null then raise exception 'authentication required'; end if; insert into public.campaigns(owner_id,nome,descricao,imagem_url,tipo,codigo_convite) values(auth.uid(),trim(p_nome),coalesce(p_descricao,''),nullif(p_imagem_url,''),p_tipo,public.generate_invite_code()) returning id into new_id; insert into public.campaign_members(campaign_id,user_id,role) values(new_id,auth.uid(),'mestre'); return new_id; end; $$;
create or replace function public.join_campaign_by_code(p_codigo text) returns uuid language plpgsql security definer set search_path=public as $$ declare campaign uuid; begin if auth.uid() is null then raise exception 'authentication required'; end if; select id into campaign from public.campaigns where codigo_convite=upper(trim(p_codigo)); if campaign is null then raise exception 'invalid invite code'; end if; insert into public.campaign_members(campaign_id,user_id,role,status) values(campaign,auth.uid(),'jogador','ativo') on conflict(campaign_id,user_id) do update set status='ativo',role=case when public.campaign_members.role='observador' then 'jogador' else public.campaign_members.role end; return campaign; end; $$;
create or replace function public.regenerate_campaign_invite(p_campaign_id uuid) returns text language plpgsql security definer set search_path=public as $$ declare code text; begin if not public.is_campaign_master(p_campaign_id) then raise exception 'master role required'; end if; code:=public.generate_invite_code(); update public.campaigns set codigo_convite=code where id=p_campaign_id; return code; end; $$;

create table if not exists public.personagens (id text primary key,nome text not null,jogador text not null default 'Jogador',conceito text not null default 'Lúcido',nivel integer not null default 1,atributos jsonb not null default '{}'::jsonb,atributo_principal text not null default 'mente',resistencia integer not null default 7,defesa integer not null default 10,vida_atual integer not null default 3,vida_maxima integer not null default 3,foco_atual integer not null default 4,foco_maximo integer not null default 4,ruptura integer not null default 0,historico_ruptura jsonb not null default '[]'::jsonb,dominios jsonb not null default '{}'::jsonb,ancoragem text not null default '',vinculos jsonb not null default '[]'::jsonb,equipamentos jsonb not null default '[]'::jsonb,recursos jsonb not null default '[]'::jsonb,criado_em timestamptz not null default now(),atualizado_em timestamptz not null default now());
alter table public.personagens add column if not exists campaign_id uuid references public.campaigns(id) on delete set null;
alter table public.personagens add column if not exists owner_user_id uuid references auth.users(id) on delete set null;
alter table public.personagens add column if not exists protecao_onirica_atual integer not null default 2;
alter table public.personagens add column if not exists protecao_onirica_maxima integer not null default 2;
alter table public.personagens add column if not exists percepcao_onirica_notas text default '';
alter table public.personagens add column if not exists anotacoes_gerais text default '';
create index if not exists personagens_campaign_idx on public.personagens(campaign_id);
create index if not exists personagens_owner_idx on public.personagens(owner_user_id);
do $$ begin if not exists(select 1 from pg_constraint where conname='campaign_members_character_fk') then alter table public.campaign_members add constraint campaign_members_character_fk foreign key(character_id) references public.personagens(id) on delete set null; end if; end $$;
create or replace function public.link_own_character_to_membership(p_campaign_id uuid,p_character_id text) returns void language plpgsql security definer set search_path=public as $$ begin if not public.is_campaign_member(p_campaign_id) then raise exception 'campaign membership required'; end if; if not exists(select 1 from public.personagens where id=p_character_id and campaign_id=p_campaign_id and owner_user_id=auth.uid()) then raise exception 'character is not owned by current user in this campaign'; end if; update public.campaign_members set character_id=p_character_id where campaign_id=p_campaign_id and user_id=auth.uid(); end; $$;

alter table public.profiles enable row level security; alter table public.campaigns enable row level security; alter table public.campaign_members enable row level security; alter table public.personagens enable row level security;
drop policy if exists "Permitir tudo em perfis" on public.profiles; drop policy if exists "Permitir tudo em personagens" on public.personagens;
drop policy if exists "users read own profile" on public.profiles; drop policy if exists "users update own profile" on public.profiles; drop policy if exists "users insert own profile" on public.profiles; drop policy if exists "campaign members can read campaigns" on public.campaigns; drop policy if exists "owners create campaigns" on public.campaigns; drop policy if exists "masters update campaigns" on public.campaigns; drop policy if exists "users can read their campaign members" on public.campaign_members; drop policy if exists "masters manage campaign members" on public.campaign_members; drop policy if exists "members can read characters" on public.personagens; drop policy if exists "owners and masters manage characters" on public.personagens;
create policy "users read own profile" on public.profiles for select using(user_id=auth.uid()); create policy "users update own profile" on public.profiles for update using(user_id=auth.uid()) with check(user_id=auth.uid()); create policy "users insert own profile" on public.profiles for insert with check(user_id=auth.uid());
create policy "campaign members can read campaigns" on public.campaigns for select using(public.is_campaign_member(id)); create policy "owners create campaigns" on public.campaigns for insert with check(owner_id=auth.uid()); create policy "masters update campaigns" on public.campaigns for update using(public.is_campaign_master(id)) with check(public.is_campaign_master(id));
create policy "users can read their campaign members" on public.campaign_members for select using(public.is_campaign_member(campaign_id)); create policy "masters manage campaign members" on public.campaign_members for update using(public.is_campaign_master(campaign_id)) with check(public.is_campaign_master(campaign_id));
create policy "members can read characters" on public.personagens for select using(campaign_id is not null and public.is_campaign_member(campaign_id)); create policy "owners and masters manage characters" on public.personagens for all using(owner_user_id=auth.uid() or (campaign_id is not null and public.is_campaign_master(campaign_id))) with check(owner_user_id=auth.uid() or (campaign_id is not null and public.is_campaign_master(campaign_id)));
revoke all on function public.create_campaign(text,text,text,text),public.join_campaign_by_code(text),public.regenerate_campaign_invite(uuid),public.link_own_character_to_membership(uuid,text) from public; grant execute on function public.create_campaign(text,text,text,text),public.join_campaign_by_code(text),public.regenerate_campaign_invite(uuid),public.link_own_character_to_membership(uuid,text) to authenticated;
