export interface CompendiumRuleTable { headers: string[]; rows: string[][]; }
export interface CompendiumRuleSection { title?: string; paragraphs?: string[]; bullets?: string[]; table?: CompendiumRuleTable; note?: string; }
export interface CompendiumRuleDocument { source: string; pages: string; sections: CompendiumRuleSection[]; }

const GUIDE = 'Livro Básico — Guia Rápido de Regras';

export const FULL_COMPENDIUM_RULES: Record<string, CompendiumRuleDocument> = {
  'teste-mundano': { source: GUIDE, pages: '153', sections: [
    { title: 'Teste Mundano', paragraphs: ['Role 1d20 + Atributo apropriado. Resultado igual ou superior à DT é sucesso. Foco pode ser usado normalmente.'], table: { headers: ['DT','Referência'], rows: [['8','Trivial'],['10','Fácil'],['12','Comum'],['14','Desafiador'],['16','Difícil'],['18','Muito Difícil'],['20','Extraordinário'],['>20','Onírico']] } },
    { title: 'Quando rolar', bullets: ['Role dados apenas quando houver incerteza relevante e uma consequência interessante para a falha.','Quando não houver incerteza relevante, a ação simplesmente acontece.'] }
  ]},
  'teste-reflexo': { source: GUIDE, pages: '153', sections: [
    { title: 'Teste Reflexo', paragraphs: ['Role 1d20 + Atributo apropriado. É um Teste Mundano pedido como resposta imediata a um gatilho narrativo: habilidade de um Adversário, perigo ambiental ou outro efeito. O Mestre determina o Atributo e a DT conforme o gatilho. Foco, Vantagem e Desvantagem podem ser usados nas condições habituais.'] }
  ]},
  'criticos': { source: GUIDE, pages: '154', sections: [
    { title: 'Críticos', bullets: ['Mundano: 20 natural é sucesso automático; se causar dano, o dano é crítico.','Onírico: Convergência é o crítico; a manifestação acontece, reduz 1 Ruptura e o dano, se houver, é crítico.','Dano crítico = valor máximo do dado + nova rolagem do dado + modificador aplicável.'] }
  ]},
  'teste-onirico': { source: GUIDE, pages: '154', sections: [
    { title: 'Teste Onírico', paragraphs: ['Role 2d20 + Atributo apropriado: um dado é Realidade e outro é Sonhar. Compare cada dado separadamente à DT. A DT é normalmente 13 e não usa a tabela de dificuldades Mundanas. Os dados não competem entre si e não existem margens de sucesso. Foco pode ser usado normalmente.'], table: { headers: ['Realidade','Sonhar','Resultado','Manifestação','Ruptura'], rows: [['Sucesso','Sucesso','Convergência','Acontece; é crítico','-1'],['Sucesso','Fracasso','Realidade vence','Não acontece','0'],['Fracasso','Sucesso','Sonhar vence','Acontece','+1'],['Fracasso','Fracasso','Divergência','Não acontece','+2']] } }
  ]},
  'ruptura': { source: GUIDE, pages: '154', sections: [
    { title: 'Ruptura', paragraphs: ['A Ruptura representa a tensão entre Realidade e Sonhar. Ao alcançar 6, resolva primeiro a manifestação que levou a trilha ao limite. Depois o Mestre estabelece um Efeito de Ruptura coerente e a trilha retorna a 0.'], bullets: ['Origem: onde o Sonhar estava agindo?','Domínio: o que foi manipulado?','Pressão: qual Dificuldade, Obstáculo ou Perigo surge?','O efeito não deve tornar a tentativa mais vantajosa nem desfazer o que ela acabou de realizar.','A consequência pode ser revelada depois na mesma Cena, mas não adiada indefinidamente.'] }
  ]},
  'delirio': { source: GUIDE, pages: '154', sections: [
    { title: 'Delírio', paragraphs: ['Quando um Velado testemunha o Sonhar vindo à Realidade, o contato com o impossível pode provocar Delírio. Quando ocorre um Delírio, todos os Desvelados presentes recebem +1 Ruptura. A quantidade de testemunhas não multiplica esse +1.'], table: { headers: ['Categoria','Leitura','Delírio?'], rows: [['Coincidente','Sutil, breve ou plausivelmente confundida com algo possível.','Não'],['Moderado','Perceptível e difícil de explicar; algo claramente parece errado.','Sim'],['Intenso','Contradiz abertamente as regras conhecidas da Realidade.','Sim']] } },
    { paragraphs: ['Delírio sempre causa Esquecimento. A mente humana não suporta o impossível. Quando o Delírio é Moderado ocorre: paralisia e respostas de medo e evitação. Quando o Delírio é Intenso ocorre: pânico, desmaio, convulsões, ou colapso mental. Dispositivos tecnológicos como fotografias, vídeos e transmissões ao vivo não provocam Delírio. Isso não quer dizer que se forem consideradas autênticas não causem estranhamento, ansiedade, medo e até pânico, mas o esquecimento e os efeitos intensos do Delírio são evitados. A DCR manipula protocolos complexos de condicionamento aos seus agentes Velados demonstrando que a mente humana quer esquecer, mas pode ainda se lembrar e se tornar imune ao Delírio.'] }
  ]},
  'criacao-desvelado': { source: GUIDE, pages: '152–153', sections: [
    { title: 'Atributos', paragraphs: ['Corpo representa força, resistência e coordenação; Mente, raciocínio, percepção e conhecimento; Vontade, determinação e autocontrole; Vínculo, conexões emocionais, sociais e simbólicas. Na criação, distribua +2, +1, 0 e -1 entre os quatro Atributos e escolha um Atributo Principal.'] },
    { title: 'Criação rápida — Nível 1', bullets: ['Escolha um Conceito: Lúcido, Tecelão, Desperto ou Ecoante.','Distribua +2, +1, 0 e -1; escolha o Atributo Principal.','Anote 4 PV, 2 PO, R = 6 + Corpo, Defesa = 8 + Corpo e 4 PF.','Distribua 5 Pontos de Sonhar entre os cinco Domínios; máximo 3 em um Domínio.','Defina Recursos e equipamentos conforme a narrativa. Recursos começam em 1.','Defina uma Ancoragem e os Vínculos do Desvelado.'] }
  ]},
  'recursos-desvelado': { source: GUIDE, pages: '152', sections: [
    { title: 'Valores essenciais', table: { headers: ['Valor','Regra'], rows: [['PV','Nível 1-2: 4 PV. Níveis 3-5: 5 PV.'],['Resistência (R)','6 + Corpo.'],['Defesa','8 + Corpo.'],['Foco (PF)','4 PF no nível 1. Antes de um Teste, gaste no máximo 1 PF para +2.'],['Proteção Onírica (PO)','2 PO. Após comparar dano à R, gaste 1 PO para reduzir em 1 PV a perda. Máximo 1 PO por ocorrência de dano.'],['Ruptura','Trilha de 0 a 6. Resultados Oníricos e Delírio alteram a trilha.']] } }
  ]},
  'progressao': { source: GUIDE, pages: '153', sections: [
    { title: 'Sonhar e Domínios', table: { headers: ['Nível','Pontos de Sonhar','Domínio máximo'], rows: [['1','5','3'],['2','7','3'],['3','8','4'],['4','9','4'],['5','10','5']] }, note: 'Pontos de Sonhar são investimento permanente e não são gastos ao usar um Domínio. Conhecer um nível concede acesso aos níveis anteriores. Apenas um Domínio pode chegar ao nível 5.' },
    { title: 'Progressão', table: { headers: ['Nível','Progressão'], rows: [['1','4 PV / 4 PF / 2 PO / 5 Pontos de Sonhar / máximo 3'],['2','+1 PF / +2 Pontos de Sonhar / nível máximo do Sonhar 3'],['3','+1 PV / +1 Atributo / +1 Ponto de Sonhar / nível máximo do Sonhar 4'],['4','+1 PF / +1 Ponto de Sonhar / nível máximo do Sonhar 4'],['5','+1 Atributo / +1 Ponto / nível máximo do Sonhar 5; apenas um Domínio 5']] } }
  ]},
  'vantagem-desvantagem': { source: GUIDE, pages: '158', sections: [
    { title: 'Vantagem e Desvantagem', paragraphs: ['Aplicam-se a Testes Mundanos e Reflexos, nunca a Testes Oníricos. Vantagem: role 2d20 e use o maior. Desvantagem: use o menor. Fontes iguais não acumulam; Vantagem e Desvantagem se anulam independentemente da quantidade.'] }
  ]},
  'condicoes': { source: GUIDE, pages: '158', sections: [
    { title: 'Condições', table: { headers: ['Condição','Efeito'], rows: [['Oculto','Ações que dependam de localizar/perceber sofrem Desvantagem se a percepção for difícil; se impossível, a ação não pode ser realizada.'],['Impedido','Se a limitação tornar uma ação impossível, ela não ocorre; se apenas dificultar significativamente, o Teste Mundano sofre Desvantagem. Não perde automaticamente Ação ou Turno.'],['Vulnerável','Testes Mundanos realizados contra um alvo Vulnerável podem receber Vantagem quando a vulnerabilidade puder ser explorada.']] } },
    { title: 'Condições e Sonhar', bullets: ['Se a causa não interfere na manifestação: Teste Onírico normal.','Se torna a manifestação significativamente mais difícil: +2 à DT Onírica.','Se elimina capacidade indispensável de perceber, identificar, alcançar ou estabelecer a manifestação: ela não pode ser realizada daquela maneira.','Aumentos de DT por Condições não acumulam; considere a mais relevante.'] }
  ]},
  'descanso': { source: GUIDE, pages: '159', sections: [
    { title: 'Descanso', paragraphs: ['Cerca de 8 horas de sono concedem 2 Movimentos de Descanso. O Desvelado pode usá-los para recuperar recursos conforme as opções de Descanso da ficha/regras da mesa. Passar tempo com sua Ancoragem concede 1 Movimento adicional. O movimento Restaurar Ruptura retorna a trilha a 0; a Proteção Onírica também pode ser recuperada por Movimento de Descanso.'] }
  ]},
  'distancias': { source: GUIDE, pages: '159', sections: [
    { title: 'Distâncias', table: { headers: ['Faixa','Referência'], rows: [['Corpo a Corpo','até 1,5 m'],['Muito Próximo','até 3 m'],['Próximo','3 a 9 m'],['Longe','9 a 15 m'],['Muito Longe','15 a 30 m'],['Além','mais de 30 até cerca de 60 m']] } }
  ]},
  'visao-cobertura': { source: GUIDE, pages: '159', sections: [
    { title: 'Visão, audição e cobertura', bullets: ['Escuridão, cegueira ou surdez: Desvantagem em Testes Mundanos dependentes do sentido.','Se o teste depender exclusivamente de um sentido indisponível, a ação pode ser impossível.','Cobertura parcial: Desvantagem em ataques contra o alvo.','Cobertura total: impede ações que exigem linha de visão.','Área pode ignorar cobertura quando a narrativa permitir.'] }
  ]},
  'contadores': { source: GUIDE, pages: '159', sections: [
    { title: 'Contadores', paragraphs: ['Use Contadores para processos, pressão, perseguições e conflitos em etapas. Defina valor inicial, objetivo, direção e gatilhos. Se o Sonhar participar, substitua a rolagem padrão pelo Teste Onírico: Convergência avança 2 no Contador favorável ao Personagem e -1 Ruptura; Realidade vence recua 1; Sonhar vence progride 1 e +1 Ruptura; Divergência recua 2 e +2 Ruptura, quando recuar fizer sentido.'] }
  ]},
  'cena-tensao': { source: GUIDE, pages: '159', sections: [
    { title: 'Combate', paragraphs: ['Não há iniciativa. Em Cena de Tensão, os Jogadores escolhem a ordem e os Turnos alternam Jogador e Mestre. A Rodada termina quando todos os Jogadores tiveram sua ativação no turno.'] }
  ]},
  'acoes-jogador': { source: GUIDE, pages: '159', sections: [
    { title: 'Ações do Jogador', bullets: ['Ataque Corpo a Corpo ou à Distância: Teste Mundano. Contra Adversário, use Dificuldade; contra Personagem, Defesa.','Agarrar, Derrubar ou Imobilizar: Teste Mundano de Corpo; sucesso pode impor Condição apropriada, normalmente Impedido.','Manipulação do Sonhar: Teste Onírico.','Ataque + Sonhar: uma única Ação e um único Teste Onírico; o Sonhar deve participar diretamente do ataque. DT = maior entre 13 e a Dificuldade do alvo.','Ajudar: concede Vantagem ao próximo Teste Mundano diretamente beneficiado; para ajudar Sonhar, gaste a Ação e o aliado reduz a DT Onírica em 2.','Interagir com ambiente/objeto torna-se Ação quando exige engajamento complexo.','Correr: Gaste sua Ação e se Desloque até Longe.'] }
  ]},
  'ajudar': { source: GUIDE, pages: '159', sections: [
    { title: 'Ajudar', paragraphs: ['Ajudar: concede Vantagem ao próximo Teste Mundano diretamente beneficiado; para ajudar Sonhar, gaste a Ação e o aliado reduz a DT Onírica em 2.'] }
  ]},
  'ataque-sonhar': { source: GUIDE, pages: '160', sections: [
    { title: 'Ataque + Sonhar', table: { headers: ['Resultado','Efeito'], rows: [['Convergência','Ataque e manifestação acontecem; crítico; -1 Ruptura.'],['Realidade vence','Ataque e manifestação falham.'],['Sonhar vence','Ataque e manifestação acontecem; +1 Ruptura.'],['Divergência','Ataque e manifestação falham; +2 Ruptura.']] } }
  ]},
  'movimento': { source: GUIDE, pages: '160', sections: [
    { title: 'Movimento', paragraphs: ['O Movimento integra a Ação e pode ser dividido antes e depois dela. Deslocamento base: Próximo. Correr exige gastar a Ação para deslocar-se até Longe, sem teste adicional. Interações simples como abrir uma porta destrancada, pegar objeto, sacar arma ou ligar lanterna integram o Movimento.'] }
  ]},
  'acoes-mestre': { source: GUIDE, pages: '160', sections: [
    { title: 'Turno do Mestre', bullets: ['Ativar um Adversário;','Ativar efeito do ambiente;','Mover a narrativa.','Mais Adversários não concedem automaticamente mais Ações ao Mestre.','Ataques de Adversários usam 1d20 contra Defesa, sem somar automaticamente Nível de Ameaça.'] }
  ]},
  'neutralizacao': { source: GUIDE, pages: '160', sections: [
    { title: 'Neutralização', paragraphs: ['Neutralizar é retirar a oposição efetiva da Cena. Pode ocorrer por imobilização, aprisionamento, expulsão, convencimento, separação do objetivo ou desfazendo o que sustenta um Pesadelo. Não há Teste de Neutralização específico e não é necessário reduzir Vida a 0.'] }
  ]},
  'principios-sonhar': { source: GUIDE, pages: '160', sections: [
    { title: 'O Sonhar', paragraphs: ['O Onírico não possui lista de poderes. O Jogador determina a intenção; o Domínio determina a possibilidade; o nível determina a profundidade; a narrativa determina a forma; o Teste Onírico determina o encontro entre Sonhar e Realidade.'] },
    { title: 'Três níveis que não devem ser confundidos', bullets: ['Nível do Desvelado/Sonhar: nível do personagem; soma-se ao dano diretamente produzido/manipulado pelo Sonhar.','Nível conhecido no Domínio: define quais possibilidades estão disponíveis.','Nível efetivamente utilizado: define alcance, duração, Potência e demais limites daquela manifestação.'] },
    { title: 'Linguagem dos níveis', table: { headers: ['Nível','Verbo','Ideia'], rows: [['1','Perceber','sentir e compreender o aspecto do Domínio'],['2','Fortalecer / Enfraquecer','intensificar ou reduzir algo que já existe'],['3','Alterar / Transformar','mudar estrutura, relação, estado ou funcionamento existente'],['4','Criar','fazer surgir algo possível dentro do Domínio'],['5','Sonhar','produzir algo impossível pelas regras conhecidas da Realidade']] } }
  ]},
  'percepcao-onirica': { source: GUIDE, pages: '161', sections: [
    { title: 'Percepção Onírica', paragraphs: ['O nível 1 de cada Domínio permite Conhecer/Perceber. Essa característica concede sensibilidade às manifestações e anomalias daquele aspecto. Perceber ou interpretar algo presente não exige Teste Onírico. A percepção não é onisciência: não revela automaticamente origem, passado, futuro, ficha, fraquezas, pensamentos ou tudo atrás de obstáculos. Informações complexas e mais detalhadas exigem um Teste Onírico.'] }
  ]},
  'dominios': { source: GUIDE, pages: '161', sections: [
    { title: 'N1 — Percepção Onírica (todos os Domínios)', paragraphs: ['O nível 1 de Consciência, Espaço, Fluxo, Substância e Vida permite perceber e compreender os aspectos correspondentes. Perceber ou interpretar algo presente normalmente não exige Teste Onírico. Detalhes complexos ou ocultos podem exigir teste. Não revela automaticamente origem, passado, futuro, fraquezas nem pensamentos.'] },
    { title: 'Consciência', paragraphs: ['Percepção, emoção, memória, pensamento e identidade.'], bullets: ['N2: intensificar/reduzir emoção, pensamento, memória ou percepção existente.','N3: transformar memória, interpretação, percepção ou traço.','N4: criar memória, emoção, convicção ou experiência sensorial possível.','N5: estados mentais impossíveis ou incompatíveis com limites conhecidos.'] },
    { title: 'Espaço', paragraphs: ['Posição, distância e relações espaciais.'], bullets: ['N2: ampliar/reduzir distâncias e movimento existentes.','N3: trocar posições, reposicionar, reorganizar configuração espacial.','N4: criar caminho, passagem ou relação espacial possível.','N5: relações espaciais impossíveis: interior maior que exterior, posições simultâneas etc.'] },
    { title: 'Fluxo', paragraphs: ['Ritmo, duração, processos e causalidade.'], bullets: ['N2: acelerar/desacelerar processo existente.','N3: alterar duração, velocidade ou ordem de acontecimentos existentes.','N4: iniciar processos ou sequências possíveis.','N5: causalidade impossível: efeito antes da causa, intervalos impossíveis etc.'] },
    { title: 'Substância', paragraphs: ['Matéria e propriedades físicas.'], bullets: ['N2: fortalecer/enfraquecer dureza, peso, temperatura ou propriedade existente.','N3: transformar matéria existente, remodelar metal, madeira em pedra, concreto em vidro.','N4: criar matéria ou objeto fisicamente possível.','N5: matéria com propriedades impossíveis.'] },
    { title: 'Vida', paragraphs: ['Organismos e processos vitais.'], bullets: ['N2: fortalecer/enfraquecer recuperação, crescimento ou capacidade biológica existente.','N3: transformar tecidos, musculatura, funções ou estruturas biológicas.','N4: criar tecidos, órgãos, plantas ou organismos biologicamente possíveis.','N5: vida além dos limites naturais; inclui restaurar alguém morto conforme a regra específica.'] },
    { title: 'Criaturas e Reinos Oníricos', paragraphs: ['Só é possível perceber ou manipular um aspecto que realmente exista. Aparência humana não garante organismo, matéria convencional ou Consciência reconhecível.'] }
  ]},
  'natureza-onirica': { source: 'Livro Básico e Livro de Adversários', pages: 'Livro Básico 125–136; Adversários 8–10', sections: [
    { title: 'Natureza e aspectos existentes', paragraphs: ['A Natureza estabelece quais aspectos da Realidade existem na criatura e podem ser afetados por Domínios. Aparência humana não garante Vida, Substância ou Consciência. A ausência do aspecto não impede manipular outros elementos da Cena.'] },
    { title: 'Humanos', bullets: ['Humano DCR: agentes e Custódios da Diretoria de Continuidade da Realidade.','Humano Custódio: Desvelado supervisionado pela DCR.','Humano Dissonante: Desvelado dos Círculos Dissonantes.'] },
    { title: 'Criaturas Oníricas e Pesadelos', bullets: [
      'Emocional: constitui-se de experiências emocionais e consciência; não possui Vida ou Substância.',
      'Manifesta: corpo onírico com processos similares à Vida; não possui Consciência.',
      'Primordial: manifestação de princípios elementares ou abstratos; não possui Espaço e Fluxo.',
      'Pesadelos podem ser Emocionais, Manifestos ou Primordiais, conforme sua Natureza.'
    ] }
  ]},
  'guia-sonhar': { source: GUIDE, pages: '162–163', sections: [
    { title: 'Guia do Sonhar', bullets: ['1. Intenção - Descreva o que muda na Realidade, não apenas o resultado desejado.','2. Domínio - Identifique o aspecto diretamente alterado. Combine apenas quando outro aspecto também precisar ser manipulado diretamente.','3. Nível - Perceber, fortalecer/enfraquecer, alterar/transformar, criar ou Sonhar. Use o menor nível capaz de realizar a mudança.','4. Alcance - Determine de onde parte e até onde chega.','5. Alvos - Por padrão, um alvo. Múltiplos alvos individuais exigem Área.','6. Duração - Determine se resolve imediatamente ou precisa permanecer sustentada.','7. Complexidade - Efeitos em etapas, sequências ou processos podem exigir Contador ou ações sucessivas.','8. Dano/Potência - Se houver dano direto, escolha intensidade e aplique Potência a uma única característica.','9. Atributo - Escolha Corpo, Mente, Vontade ou Vínculo conforme a abordagem narrada.','10. Teste - Role Realidade e Sonhar, compare à DT e aplique manifestação, Ruptura, dano e consequências.'] },
    { title: 'Alcance máximo', table: { headers: ['Nível efetivo','Alcance'], rows: [['1','Muito Próximo'],['2','Próximo - requer Espaço 2 para alcançar nessa faixa'],['3','Longe – requer Espaço 3 para alcançar nessa faixa'],['4','Muito Longe – requer Espaço 4 para alcançar nessa faixa'],['5','Além – requer Espaço 5 para alcançar nessa faixa']] } },
    { title: 'Duração', table: { headers: ['Nível','Referência'], rows: [['1','Instantâneo'],['2','1 Rodada'],['3','1 Rodada'],['4','1 Cena'],['5','1 Cena']] }, note: 'Duração sustenta a alteração; não apaga consequências já produzidas. Uma distância artificial volta ao normal quando o efeito termina, mas alguém que caiu por causa dela continua caído. Criar matéria ou tecido não os torna automaticamente permanentes.' },
    { title: 'Combinação de Domínios', bullets: ['O Domínio Principal deve possuir nível ao menos 1 maior que cada secundário.','Não some os níveis. Cada Domínio precisa permitir sua parte da manifestação.','Para Potência, use o maior nível de Domínio combinado.','A combinação não concede um conjunto separado de Passos para cada Domínio.'] },
    { title: 'Tentativas sucessivas', paragraphs: ['Depois de uma falha, não repita o mesmo teste até obter sucesso. Mude alvo, circunstâncias, uso do Domínio ou outro elemento relevante. O Mestre decide se a mudança constitui uma nova tentativa.'] }
  ]},
  'alcance-sonhar': { source: GUIDE, pages: '162', sections: [{ title: 'Alcance máximo', table: { headers: ['Nível efetivo','Alcance'], rows: [['1','Muito Próximo'],['2','Próximo - requer Espaço 2 para alcançar nessa faixa'],['3','Longe – requer Espaço 3 para alcançar nessa faixa'],['4','Muito Longe – requer Espaço 4 para alcançar nessa faixa'],['5','Além – requer Espaço 5 para alcançar nessa faixa']] } }] },
  'duracao-sonhar': { source: GUIDE, pages: '162', sections: [{ title: 'Duração', table: { headers: ['Nível','Referência'], rows: [['1','Instantâneo'],['2','1 Rodada'],['3','1 Rodada'],['4','1 Cena'],['5','1 Cena']] }, note: 'Duração sustenta a alteração; não apaga consequências já produzidas. Uma distância artificial volta ao normal quando o efeito termina, mas alguém que caiu por causa dela continua caído. Criar matéria ou tecido não os torna automaticamente permanentes.' }] },
  'combinacao-dominios': { source: GUIDE, pages: '162', sections: [{ title: 'Combinação de Domínios', bullets: ['O Domínio Principal deve possuir nível ao menos 1 maior que cada secundário.','Não some os níveis. Cada Domínio precisa permitir sua parte da manifestação.','Para Potência, use o maior nível de Domínio combinado.','A combinação não concede um conjunto separado de Passos para cada Domínio.'] }] },
  'tentativas-sucessivas': { source: GUIDE, pages: '163', sections: [{ title: 'Tentativas sucessivas', paragraphs: ['Depois de uma falha, não repita o mesmo teste até obter sucesso. Mude alvo, circunstâncias, uso do Domínio ou outro elemento relevante. O Mestre decide se a mudança constitui uma nova tentativa.'] }] },
  'potencia': { source: GUIDE, pages: '163', sections: [
    { title: 'Potência do Sonhar', paragraphs: ['Nível responde “o que é possível?”. Potência responde “quanto uma característica é afetada?”.'], table: { headers: ['Nível','Passos'], rows: [['1','Percepção Onírica'],['2','1 Passo'],['3','2 Passos'],['4','2 Passos'],['5','3 Passos']] }, note: 'REGRA CENTRAL Escolha UMA característica por manifestação e aplique nela todos os Passos disponíveis. Não distribua Passos entre Dano, Defesa, Área, Resistência ou outras características.' },
    { title: 'Parâmetros', table: { headers: ['Parâmetro','Efeito por Passo de Potência'], rows: [['Área*','±1 faixa; Base Alvo.'],['Contador','±1 em um Contador'],['Dano**','±1 categoria de dado'],['Defesa/Dificuldade','±1'],['Deslocamento','1 Passo: Longe; 2 Passos: Muito Longe; 3 Passos: Além'],['Quantidade','±1 unidade'],['Resistência','±1'],['Resistência de materiais','±1 categoria'],['Tamanho','±1 categoria; base Médio.'],['Testes','±1 bônus']] } },
    { paragraphs: ['* Área pode ser alterada com Passos de Potência quando a narrativa justificar sua expansão (ex: gás, chamas, etc) ou velocidade (golpear alvos em uma Área ao Alcance).','** O d20 continua sendo dado de dano especial e não pode ser alcançado com Passos de Potência.','Dano progride d4 → d6 → d8 → d10 → d12. Potência não eleva automaticamente para d20; d20 é excepcional e ligado a fenômenos Oníricos poderosos ou Sonhar 5.','Uma manifestação pode gerar várias consequências naturais sem pagar um Passo por cada uma. Isso não permite obter vários benefícios mecânicos independentes. Potência mede uma característica; a narrativa determina repercussões.'] }
  ]},
  'objetos-estruturas': { source: GUIDE, pages: '164', sections: [
    { title: 'Objetos e estruturas', paragraphs: ['Objetos e estruturas não precisam de PV. Compare dano diretamente à Resistência estrutural: dano ≤ R, resiste; dano > R, quebra, perfura, rompe ou é destruído conforme a ação. A fonte precisa ser capaz de afetar o material daquela maneira. Danos inferiores não se acumulam, salvo deterioração persistente justificada.'], table: { headers: ['Material','Pequeno','Médio','Grande','Imenso'], rows: [['Frágil','4','6','8','10'],['Comum','6','8','10','12'],['Resistente','8','10','12','14'],['Muito Resistente','10','12','14','16']] } },
    { paragraphs: ['Para Potência em estruturas, Resistência de materiais move categorias Frágil → Comum → Resistente → Muito Resistente. Tamanho parte de Médio e move categorias. Escolher Tamanho não aumenta simultaneamente Resistência.'] }
  ]},
  'vida-cura-ferimento': { source: GUIDE, pages: '164', sections: [
    { title: 'Vida: cura e ferimento', paragraphs: ['Toda cura ou agressão deve explicar a alteração biológica. Recuperar PV não substitui a avaliação de nível e da mudança realizada.'], table: { headers: ['Vida','Recuperação','Ferimento'], rows: [['1','Perceber','Perceber'],['2','fortalecer recuperação','enfraquecer recuperação'],['3','1 PV - regenerar/reparar tecidos gravemente danificados','1 PV - alterar tecidos, estruturas ou funções e provocar novos ferimentos'],['4','2 PV - criar tecidos/estruturas/processos de recuperação','2 PV - criar tecidos/estruturas/processos capazes de ferir'],['5','3 PV - restaurar além dos limites naturais','3 PV - ferir/alterar além dos limites naturais']] } },
    { bullets: ['Cura não aumenta por Passos de Potência.','Convergência não aumenta automaticamente a cura; Divergência não produz cura parcial.','Cura não remove automaticamente venenos, doenças ou Condições; trate a causa com nível adequado.','Quando Vida causa ferimento, use a tabela específica de Vida: Cura e Ferimento, respeitando o nível efetivamente utilizado.','Vida 4 pode preservar/restaurar funções vitais de alguém vivo, mas não reverte morte determinada pelo Movimento de Morte.','Vida 5 pode restaurar alguém morto; sucesso retorna com 1 PV. Corpo, tempo e circunstâncias podem exigir outros Domínios.'] }
  ]},
  'efeitos-ativos': { source: GUIDE, pages: '164–165', sections: [
    { title: 'DT do Sonhar', table: { headers: ['Nível do Domínio','DT para agir contra a manifestação'], rows: [['1','10'],['2','12'],['3','14'],['4','16'],['5','18']] } },
    { paragraphs: ['A manifestação acontece primeiro. Um alvo não recebe imediatamente um segundo teste para negá-la. Teste contra a DT do Sonhar somente quando alguém tentar uma ação diretamente dificultada pelo efeito e houver forma coerente de enfrentá-lo.'], bullets: ['Sucesso permite agir contra a manifestação naquela tentativa; não a dissipa automaticamente.','Se o efeito interfere apenas no Movimento, falha impede o deslocamento, mas não consome automaticamente a Ação.','Se interfere diretamente em uma Ação, falha impede a Ação e ela é utilizada.','Múltiplas manifestações sobre a mesma tentativa: faça um único teste contra a maior DT aplicável.','Pesadelo que confronta manifestação ativa: 1d20 + Nível de Ameaça contra DT do Sonhar. Esse bônus não se aplica automaticamente a ataques.'] }
  ]},
  'conflitos-personagens': { source: GUIDE, pages: '165', sections: [
    { title: 'Conflitos entre personagens', paragraphs: ['Mundano: maior resultado vence; empate por nova rolagem ou solução apropriada. Onírico: cada personagem faz seu Teste Onírico contra DT 13 e aplica normalmente manifestação e Ruptura. Se apenas um efeito acontece, ele prevalece. Se ambos acontecem e conflitam, faça Teste Onírico de desempate: Convergência > Sonhar vence > Realidade vence > Divergência; o desempate não gera efeitos nem Ruptura.'] }
  ]},
  'dano': { source: GUIDE, pages: '158', sections: [
    { title: 'Converter dano em perda de PV', bullets: ['Dano ≤ R: perde 1 PV.','Dano > R: perde 2 PV.','Regra opcional - Dano Massivo: dano > 2 × R: perde 3 PV.','Depois da comparação, um Desvelado pode gastar 1 PO para reduzir a perda em 1 PV.'] },
    { title: 'Área e dano contínuo', paragraphs: ['Em Área, faça um único teste contra a maior Defesa ou Dificuldade dos alvos. Role o dano uma vez e aplique o mesmo resultado a todos os atingidos. Área não é automática: precisa ser coerente com a fonte. Perigos contínuos repetem o mesmo dado ao fim de cada Rodada enquanto a exposição continuar.'] }
  ]},
  'movimento-morte': { source: GUIDE, pages: '158', sections: [
    { title: 'Movimento de Morte', paragraphs: ['Ao chegar a 0 PV, role 2d20 sem Atributo, um de Realidade e um de Sonhar, cada um contra DT 13.'], table: { headers: ['Resultado','Destino'], rows: [['Convergência','Consciente. Recupere 2 PV.'],['Realidade vence','Estabiliza. Permanece inconsciente com 0 PV e precisa de cuidados ou Descanso.'],['Sonhar vence','Consciente. Recupere 1 PV e +1 Ruptura.'],['Divergência','O Personagem morre.']] }, note: 'O jogador descreve como o Sonhar devolve sua vida ou como a Realidade a tira.' }
  ]},
  'intensidade-dano': { source: GUIDE, pages: '155–157', sections: [
    { title: 'Exemplos de Armas e Armamentos Mundanos', table: { headers: ['Arma / Armamento','Dano típico','Área','Distância Máxima','Exemplos / Referência'], rows: [['Ataque desarmado','d4','Alvo','CaC','Soco, chute, cabeçada'],['Objeto improvisado','d4','Alvo','Muito Próximo','Garrafa, ferramenta pequena, objeto contundente'],['Arma contundente','d6','Alvo','CaC','Cassetete, bastão, taco de baseball'],['Arma branca curta','d6','Alvo','CaC','Faca, canivete, punhal'],['Arma branca pesada','d8','Alvo','CaC','Machado, facão, lâmina grande'],['Arma curta','d8','Alvo','Longe','Pistola, revólver'],['Submetralhadora','d8','Alvo','Longe','Rajadas de calibre de arma curta'],['Espingarda','d10','Alvo / Muito Próximo','Próximo','Disparo de curta distância'],['Fuzil','d10','Alvo','Muito Longe','Fuzil de assalto ou de precisão'],['Metralhadora','d10','Alvo / Muito Próximo','Muito Longe','Fogo automático sustentado'],['Granada','d10','Muito Próximo','Próximo','Explosão e fragmentação'],['Explosivo pesado','d12','Próximo','Longe','Carga explosiva, bomba de grande potência']] }, note: 'Legenda: CaC: Corpo a Corpo' },
    { title: 'Exemplos de Danos de Efeitos Ambientais', table: { headers: ['Situação Ambiental','Dano típico','Área','Exemplos'], rows: [['Impacto ou queda pequena','d4','Alvo','Queda curta, ser lançado contra uma parede, destroços pequenos'],['Calor ou chama localizada','d4','Alvo','Contato breve com fogo, superfície muito quente'],['Queda relevante','d6','Alvo','Queda de um pavimento, escada ou estrutura elevada'],['Incêndio localizado','d6','Alvo / Muito Próximo','Pessoa em chamas, pequena área incendiada'],['Colisão moderada','d6','Alvo / Muito Próximo','Atropelamento em baixa velocidade, impacto de motocicleta'],['Queda elevada','d8','Alvo','Queda de vários metros ou pavimentos'],['Colisão violenta','d8','Alvo / Muito Próximo','Atropelamento em velocidade, acidente automobilístico grave'],['Incêndio intenso','d8','Muito Próximo','Cômodo tomado pelo fogo, exposição intensa às chamas'],['Eletrocussão severa','d8','Alvo','Rede elétrica de alta potência, equipamento industrial'],['Esmagamento','d10','Alvo','Veículo, maquinário ou estrutura pesada'],['Explosão','d10','Muito Próximo','Explosão de combustível, equipamento ou instalação'],['Desabamento','d10','Muito Próximo / Próximo','Parte de teto, parede ou estrutura desmoronando'],['Colisão extrema','d10','Alvo / Muito Próximo','Acidente rodoviário de alta energia'],['Catástrofe localizada','d12','Próximo','Grande explosão, colapso estrutural severo'],['Destruição massiva','d12','Próximo ou maior','Desabamento de grande estrutura, explosão industrial devastadora']] } },
    { title: 'Exemplos de Danos de Origem do Sonhar', table: { headers: ['Manifestação do Sonhar','Dano típico','Exemplos'], rows: [['Consequência limitada','d4','Pequeno impacto ou pressão; queimadura superficial; substância irritante; dor ou sobrecarga sensorial breve; alteração de movimento que provoque impacto leve.'],['Consequência moderada','d6','Corte ou queimadura relevante; substância corrosiva; queda provocada; compressão espacial; trauma biológico localizado; sobrecarga mental dolorosa; intensificação perigosa de um processo em curso'],['Consequência grave','d8','Impacto violento; queimadura grave; substância altamente corrosiva; esmagamento parcial; lesão biológica significativa; distorção espacial perigosa; sobrecarga psíquica severa; aceleração extrema de um fenômeno danoso'],['Consequência severa','d10','Grande impacto ou esmagamento; explosão localizada; dano biológico extenso; distorção espacial destrutiva; manifestação mental de violência extrema; intensificação brutal de um processo destrutivo'],['Consequência devastadora','d12','Colapso estrutural; destruição extensa de matéria ou tecido vivo; fenômeno espacial devastador; manifestação psíquica de intensidade extraordinária; processo destrutivo levado a proporções extrema.'],['Manifestação além da referência física','d20','Manifestação Onírica excepcional cuja consequência ultrapasse referências convencionais de dano']] } },
    { paragraphs: ['Área padrão: Alvo, em uma área de tamanho médio (equivalente a uma pessoa).','Alcance padrão: até Muito Próximo, acima dessa categoria requer Espaço (ver Potência do Sonhar).','Dano de fontes do Sonhar: dado de dano + nível de Personagem.','Dano de Criaturas Oníricas: dado de dano + nível de Ameaça.'] }
  ]},
  'arbitragem-mestre': { source: GUIDE, pages: '165', sections: [
    { title: 'Arbitrando o Sonhar', bullets: ['Não procure uma habilidade pronta. Identifique intenção, Domínio, nível, alcance, alvos, duração, Potência e consequência.','Não negue uma manifestação apenas porque é criativa. Se respeita os limites, permita a tentativa.','Não conceda resultado mecânico ilimitado por descrição extrema. “Transformo o coração” ou “faço uma bala infinitamente rápida” continuam sujeitos a nível, Potência, dano, R, alcance e duração.','Combine Domínios somente quando aspectos diferentes precisarem ser manipulados diretamente.','Quando mais de um Domínio parecer servir, escolha aquele que corresponde ao aspecto realmente alterado.','Se não souber, faça uma decisão coerente, registre e continue a sessão. O playtest precisa capturar essas dúvidas.'] }
  ]},
  'quando-nao-pedir-teste': { source: GUIDE, pages: '165', sections: [
    { title: 'Quando não pedir teste', paragraphs: ['Não role quando não houver incerteza relevante ou consequência interessante. Não use testes para impedir ações que já são impossíveis pela ficção; explique por que são impossíveis. Não transforme uma investigação em sequência de testes obrigatórios quando a pista pode ser descoberta por abordagem coerente.'] }
  ]},
  'pressao-cena': { source: GUIDE, pages: '165', sections: [
    { title: 'Consequência e pressão', paragraphs: ['Falhas e Rupturas devem mover a situação, não apenas bloquear. Use ambiente, tempo, atenção indesejada, perda de posição, Condições, Contadores, perigo ou novas escolhas. Seja consistente, não idêntico: situações semelhantes devem seguir o mesmo princípio, mas a ficção pode mudar a consequência.'] }
  ]},
  'delirio-mesa': { source: GUIDE, pages: '165', sections: [
    { title: 'Delírio em mesa', paragraphs: ['Pergunte se um Velado percebeu algo impossível, com que clareza e se existe explicação plausível. Leve não gera Delírio; Moderado e Intenso geram. O efeito mecânico continua +1 Ruptura para todos os Desvelados presentes.'] }
  ]},
  'ficha-adversario': { source: GUIDE, pages: '166', sections: [
    { title: 'Ficha mínima', paragraphs: ['Um Adversário precisa de Dificuldade, Vida, Resistência, Nível de Ameaça, Passivas, Ações e, quando necessário, Reações.'], table: { headers: ['NA','Vida','Mod. dano quando aplicável'], rows: [['1','3','+1'],['2','5','+2'],['3','7','+3'],['4','9','+4'],['5','12','+5']] } },
    { title: 'Dificuldade', table: { headers: ['Dificuldade','Valor'], rows: [['Baixa','12'],['Padrão','14'],['Alta','16'],['Monstruosidade','>16']] } },
    { title: 'Resistência', table: { headers: ['Resistência','Valor'], rows: [['Baixa','5'],['Padrão','6'],['Alta','8'],['Extrema','10']] } },
    { title: 'Perigo', table: { headers: ['Perigo','Dado'], rows: [['Baixo','d4'],['Moderado','d6'],['Grave','d8'],['Severo','d10'],['Devastador','d12'],['Onírico','d20 - excepcional']] }, note: 'Quando o dano escala com NA, use dado do Nível de Perigo + NA. O NA aumenta potência, mas não escolhe o dado. d20 não é simplesmente “mais forte”: representa o impossível ferindo diretamente a existência/Realidade.' },
    { title: 'Ações, Passivas e Reações', bullets: ['Passiva: característica sempre presente ou acionada sem consumir Ação.','Ação: descreva o que faz, alvo, alcance, teste, dano e consequências.','Ação sem dano pode impor Condição, alterar ambiente, separar personagens ou mudar a ficção.','Reação exige gatilho claro e, salvo indicação contrária, cada Reação pode ser usada uma vez por Rodada.'] },
    { title: 'Criação rápida de Adversário', bullets: ['Escolha NA 1-5.','Escolha Dificuldade 12/14/16.','Escolha Vida pela tabela.','Escolha R 5/6/8/10.','Defina Passivas, Ações e Reações.','Para cada Ação ofensiva, escolha Nível de Perigo coerente.'] }
  ]},
  'referencia-rapida': { source: GUIDE, pages: '167', sections: [
    { title: 'Fluxo de uma manifestação', paragraphs: ['INTENÇÃO → DOMÍNIO → NÍVEL → COMBINAÇÃO? → ALCANCE → ALVOS/ÁREA → DURAÇÃO → POTÊNCIA → ATRIBUTO → DT → TESTE ONÍRICO → MANIFESTAÇÃO → RUPTURA/DELÍRIO → CONSEQUÊNCIAS'] },
    { title: 'Checklist do Mestre', bullets: ['O Domínio realmente manipula esse aspecto?','O nível efetivo permite esse tipo de mudança?','Há combinação? Principal ≥ secundário +1?','O alvo está no alcance? Espaço é necessário?','É um alvo ou Área?','Quanto tempo o efeito precisa permanecer?','Qual UMA característica recebe Potência?','Há dano? Qual intensidade? Soma nível do Desvelado?','Qual Atributo representa a abordagem?','DT 13 ou existe regra específica?','Velados perceberam o impossível? Há Delírio?','Se a manifestação permanecer, qual DT do Sonhar será usada para agir contra ela?'] }
  ]}
};

export const getFullCompendiumRule = (id: string) => FULL_COMPENDIUM_RULES[id] || null;
