import React, { useState } from 'react';
import { Personagem } from '../types/character';
import { UserSession } from '../types/auth';
import { isSupabaseConfigured } from '../lib/supabaseClient';
import { authService } from '../services/auth/authService';

interface LoginScreenProps { personagens: Personagem[]; onLogin: (session: UserSession) => void; onAbrirModalSql: () => void; onCriarNovoPersonagem: (nome?: string) => Personagem; }

export const LoginScreen: React.FC<LoginScreenProps> = ({ personagens, onLogin, onAbrirModalSql, onCriarNovoPersonagem }) => {
  const remoto = isSupabaseConfigured();
  const [modo, setModo] = useState<'entrar' | 'cadastro' | 'local'>('entrar');
  const usarRemoto = remoto && modo !== 'local';
  const [email, setEmail] = useState(''); const [senha, setSenha] = useState(''); const [nome, setNome] = useState(''); const [codigo, setCodigo] = useState('ONIRICO-01'); const [erro, setErro] = useState(''); const [mensagem, setMensagem] = useState('');
  const concluirAuth = async (user: { id: string; email?: string; user_metadata: Record<string, unknown> }) => { const perfil = await authService.perfil(user as any); onLogin({ id: user.id, authUserId: user.id, role: 'observador', nome: perfil.nome, email: user.email, mesaCodigo: '', modoConexao: 'supabase' }); };
  const autenticar = async (e: React.FormEvent) => { e.preventDefault(); setErro(''); setMensagem(''); try { if (modo === 'cadastro') { const data = await authService.cadastrar(email, senha, nome || email.split('@')[0]); if (data.session && data.user) await concluirAuth(data.user); else setMensagem('Conta criada. Confirme seu e-mail antes de entrar.'); } else { const session = await authService.entrar(email, senha); if (session?.user) await concluirAuth(session.user); } } catch (err: any) { setErro(err.message || 'Não foi possível autenticar.'); } };
  const recuperar = async () => { setErro(''); try { await authService.recuperarSenha(email); setMensagem('Enviamos as instruções de recuperação para seu e-mail.'); } catch (err: any) { setErro(err.message || 'Não foi possível iniciar a recuperação.'); } };
  const entrarLocal = (e: React.FormEvent) => { e.preventDefault(); const personagem = personagens[0] || onCriarNovoPersonagem(nome || 'Novo Desvelado'); onLogin({ id: `local-${Date.now()}`, role: 'mestre', nome: nome || 'Narrador Onírico', mesaCodigo: codigo.toUpperCase(), personagemVinculadoId: personagem.id, modoConexao: 'local' }); };
  return <div className="min-h-screen bg-[#0B0B0B] text-[#D9D7D2]"><header className="border-b border-[#292929] px-6 py-5"><div className="mx-auto flex max-w-5xl items-center justify-between"><span className="font-serif tracking-[.16em] text-[#F5F3EE]">REINOS ONÍRICOS</span><button onClick={onAbrirModalSql} className="text-xs text-[#A88952]">Configurar Supabase</button></div></header><main className="mx-auto max-w-md px-6 py-20"><p className="ro-eyebrow text-center">Arquivo de campanha</p><h1 className="mt-3 text-center font-serif text-5xl text-[#F5F3EE]">{usarRemoto ? (modo === 'cadastro' ? 'Criar conta' : 'Entrar') : 'Acesso local'}</h1><p className="mt-4 text-center text-sm text-[#666666]">{usarRemoto ? 'Sua identidade acompanha suas campanhas, nunca um papel global.' : 'Configure o Supabase para ativar identidades e campanhas remotas.'}</p>{remoto && <div className="mt-8 grid grid-cols-2 border border-[#292929] p-1"><button type="button" onClick={() => setModo('entrar')} className={modo === 'entrar' ? 'bg-[#292929] py-2 text-xs' : 'py-2 text-xs text-[#666666]'}>Entrar</button><button type="button" onClick={() => setModo('cadastro')} className={modo === 'cadastro' ? 'bg-[#292929] py-2 text-xs' : 'py-2 text-xs text-[#666666]'}>Criar conta</button></div>}<form onSubmit={usarRemoto ? autenticar : entrarLocal} className="mt-6 space-y-4 border border-[#292929] bg-[#171717] p-6">{(modo === 'cadastro' || !usarRemoto) && <input value={nome} onChange={e => setNome(e.target.value)} placeholder="Seu nome" className="w-full border border-[#292929] bg-[#0B0B0B] p-3 text-sm" />}{usarRemoto ? <><input type="email" required value={email} onChange={e => setEmail(e.target.value)} placeholder="E-mail" className="w-full border border-[#292929] bg-[#0B0B0B] p-3 text-sm" /><input type="password" required minLength={6} value={senha} onChange={e => setSenha(e.target.value)} placeholder="Senha" className="w-full border border-[#292929] bg-[#0B0B0B] p-3 text-sm" /><button type="button" onClick={recuperar} className="text-xs text-[#A88952]">Recuperar senha</button></> : <input value={codigo} onChange={e => setCodigo(e.target.value)} placeholder="Código local" className="w-full border border-[#292929] bg-[#0B0B0B] p-3 text-sm" />} {erro && <p className="text-xs text-rose-400">{erro}</p>}{mensagem && <p className="text-xs text-[#A88952]">{mensagem}</p>}<button className="ro-button w-full">{usarRemoto ? (modo === 'cadastro' ? 'Criar conta' : 'Entrar') : 'Entrar localmente'}</button></form>{remoto && <button type="button" onClick={() => setModo('local')} className="mt-4 w-full text-xs text-[#666666]">Usar modo local de demonstração</button>}</main></div>;
};
