import { RealtimeChannel } from '@supabase/supabase-js';
import { supabase } from '../../lib/supabaseClient';
import { Contador, ConteudoDeCena, MapaNarrativo, TokenMapa } from '../../types/campaign';

export interface LiveSessionState { campaignId: string; sessionId?: string; activeSceneId?: string; activeMapId?: string; contentType: ConteudoDeCena; ruptureGeneral: number; metadata: Record<string, unknown>; updatedBy: string; updatedAt: string; }
export interface CharacterResourceUpdate { id: string; vidaAtual: number; focoAtual: number; ruptura: number; protecaoOniricaAtual: number; updatedAt: string; }
type Row = Record<string, any>;
const client = () => { if (!supabase) throw new Error('Supabase não está configurado.'); return supabase; };
const counter = (row: Row): Contador => ({ id: row.id, campanhaId: row.campaign_id, sessaoId: row.session_id || undefined, cenaId: row.scene_id || undefined, nome: row.nome, descricao: row.descricao || undefined, tipo: row.tipo, valorAtual: row.valor_atual, valorMaximo: row.valor_maximo, direcao: row.direcao, visibilidade: row.visibilidade, gatilho: row.gatilho || undefined, estado: row.estado, criadoEm: row.criado_em, atualizadoEm: row.atualizado_em, criadoPor: row.criado_por || undefined });
const map = (row: Row): MapaNarrativo => ({ id: row.id, campanhaId: row.campaign_id, titulo: row.titulo, imagemUrl: row.imagem_url || undefined, storagePath: row.storage_path || undefined, visibilidade: row.visibilidade, gradeVisivel: row.grade_visivel, criadoEm: row.criado_em, atualizadoEm: row.atualizado_em, criadoPor: row.criado_por || undefined });
const token = (row: Row): TokenMapa => ({ id: row.id, mapaId: row.map_id, campanhaId: row.campaign_id, tipo: row.tipo, nome: row.nome, imagemUrl: row.imagem_url || undefined, cor: row.cor, x: row.x, y: row.y, oculto: row.oculto, criadoEm: row.criado_em, atualizadoEm: row.atualizado_em, criadoPor: row.criado_por || undefined });
const state = (row: Row): LiveSessionState => ({ campaignId: row.campaign_id, sessionId: row.session_id || undefined, activeSceneId: row.active_scene_id || undefined, activeMapId: row.active_map_id || undefined, contentType: row.content_type, ruptureGeneral: row.rupture_general, metadata: row.metadata || {}, updatedBy: row.updated_by, updatedAt: row.updated_at });
const characterResource = (row: Row): CharacterResourceUpdate => ({ id: row.id, vidaAtual: row.vida_atual, focoAtual: row.foco_atual, ruptura: row.ruptura, protecaoOniricaAtual: row.protecao_onirica_atual, updatedAt: row.atualizado_em });
const toCounter = (item: Omit<Contador, 'id' | 'criadoEm' | 'atualizadoEm'>) => ({ campaign_id: item.campanhaId, session_id: item.sessaoId || null, scene_id: item.cenaId || null, nome: item.nome, descricao: item.descricao || null, tipo: item.tipo, valor_atual: item.valorAtual, valor_maximo: item.valorMaximo, direcao: item.direcao, visibilidade: item.visibilidade, gatilho: item.gatilho || null, estado: item.estado });
const toMap = (item: Omit<MapaNarrativo, 'id' | 'criadoEm' | 'atualizadoEm'>) => ({ campaign_id: item.campanhaId, titulo: item.titulo, imagem_url: item.imagemUrl || null, storage_path: item.storagePath || null, visibilidade: item.visibilidade, grade_visivel: item.gradeVisivel || false });
const toToken = (item: Omit<TokenMapa, 'id' | 'criadoEm' | 'atualizadoEm'>) => ({ map_id: item.mapaId, campaign_id: item.campanhaId, tipo: item.tipo, nome: item.nome, imagem_url: item.imagemUrl || null, cor: item.cor, x: item.x, y: item.y, oculto: item.oculto });

export const liveTableRepository = {
  async load(campaignId: string) { const api = client(); const [s, c, m, t] = await Promise.all([api.from('live_session_states').select('*').eq('campaign_id', campaignId).maybeSingle(), api.from('session_counters').select('*').eq('campaign_id', campaignId).order('criado_em'), api.from('narrative_maps').select('*').eq('campaign_id', campaignId).order('criado_em'), api.from('map_tokens').select('*').eq('campaign_id', campaignId).order('criado_em')]); for (const result of [s, c, m, t]) if (result.error) throw result.error; return { state: s.data ? state(s.data) : undefined, counters: (c.data || []).map(counter), maps: (m.data || []).map(map), tokens: (t.data || []).map(token) }; },
  async saveState(campaignId: string, userId: string, patch: Partial<LiveSessionState>) { const { data, error } = await client().from('live_session_states').upsert({ campaign_id: campaignId, updated_by: userId, content_type: patch.contentType || 'ambientacao', active_scene_id: patch.activeSceneId || null, active_map_id: patch.activeMapId || null, rupture_general: patch.ruptureGeneral || 0, metadata: patch.metadata || {} }, { onConflict: 'campaign_id' }).select().single(); if (error) throw error; return state(data); },
  async addCounter(item: Omit<Contador, 'id' | 'criadoEm' | 'atualizadoEm'>) { const { data, error } = await client().from('session_counters').insert(toCounter(item)).select().single(); if (error) throw error; return counter(data); },
  async patchCounter(id: string, patch: Partial<Contador>) { const values: Row = {}; if (patch.nome !== undefined) values.nome = patch.nome; if (patch.descricao !== undefined) values.descricao = patch.descricao; if (patch.valorAtual !== undefined) values.valor_atual = patch.valorAtual; if (patch.valorMaximo !== undefined) values.valor_maximo = patch.valorMaximo; if (patch.visibilidade !== undefined) values.visibilidade = patch.visibilidade; if (patch.estado !== undefined) values.estado = patch.estado; if (patch.gatilho !== undefined) values.gatilho = patch.gatilho; const { data, error } = await client().from('session_counters').update(values).eq('id', id).select().single(); if (error) throw error; return counter(data); },
  async removeCounter(id: string) { const { error } = await client().from('session_counters').delete().eq('id', id); if (error) throw error; },
  async addMap(item: Omit<MapaNarrativo, 'id' | 'criadoEm' | 'atualizadoEm'>) { const { data, error } = await client().from('narrative_maps').insert(toMap(item)).select().single(); if (error) throw error; return map(data); },
  async patchMap(id: string, patch: Partial<MapaNarrativo>) { const values: Row = {}; if (patch.titulo !== undefined) values.titulo = patch.titulo; if (patch.imagemUrl !== undefined) values.imagem_url = patch.imagemUrl; if (patch.storagePath !== undefined) values.storage_path = patch.storagePath; if (patch.visibilidade !== undefined) values.visibilidade = patch.visibilidade; if (patch.gradeVisivel !== undefined) values.grade_visivel = patch.gradeVisivel; const { data, error } = await client().from('narrative_maps').update(values).eq('id', id).select().single(); if (error) throw error; return map(data); },
  async removeMap(id: string) { const { error } = await client().from('narrative_maps').delete().eq('id', id); if (error) throw error; },
  async addToken(item: Omit<TokenMapa, 'id' | 'criadoEm' | 'atualizadoEm'>) { const { data, error } = await client().from('map_tokens').insert(toToken(item)).select().single(); if (error) throw error; return token(data); },
  async patchToken(id: string, patch: Partial<TokenMapa>) { const values: Row = {}; if (patch.nome !== undefined) values.nome = patch.nome; if (patch.imagemUrl !== undefined) values.imagem_url = patch.imagemUrl; if (patch.cor !== undefined) values.cor = patch.cor; if (patch.x !== undefined) values.x = patch.x; if (patch.y !== undefined) values.y = patch.y; if (patch.oculto !== undefined) values.oculto = patch.oculto; const { data, error } = await client().from('map_tokens').update(values).eq('id', id).select().single(); if (error) throw error; return token(data); },
  async removeToken(id: string) { const { error } = await client().from('map_tokens').delete().eq('id', id); if (error) throw error; },
  async patchCharacterResources(id: string, patch: Partial<CharacterResourceUpdate>) { const values: Row = {}; if (patch.vidaAtual !== undefined) values.vida_atual = patch.vidaAtual; if (patch.focoAtual !== undefined) values.foco_atual = patch.focoAtual; if (patch.ruptura !== undefined) values.ruptura = patch.ruptura; if (patch.protecaoOniricaAtual !== undefined) values.protecao_onirica_atual = patch.protecaoOniricaAtual; const { data, error } = await client().from('personagens').update(values).eq('id', id).select().single(); if (error) throw error; return characterResource(data); },
  subscribe(campaignId: string, handlers: { state: (item: LiveSessionState) => void; counter: (event: string, item: Contador) => void; map: (event: string, item: MapaNarrativo) => void; token: (event: string, item: TokenMapa) => void; character: (item: CharacterResourceUpdate) => void; status: (value: string) => void; }): RealtimeChannel { return client().channel(`live-table:${campaignId}`).on('postgres_changes', { event: '*', schema: 'public', table: 'live_session_states', filter: `campaign_id=eq.${campaignId}` }, payload => handlers.state(state(payload.new))).on('postgres_changes', { event: '*', schema: 'public', table: 'session_counters', filter: `campaign_id=eq.${campaignId}` }, payload => handlers.counter(payload.eventType, counter((payload.new || payload.old) as Row))).on('postgres_changes', { event: '*', schema: 'public', table: 'narrative_maps', filter: `campaign_id=eq.${campaignId}` }, payload => handlers.map(payload.eventType, map((payload.new || payload.old) as Row))).on('postgres_changes', { event: '*', schema: 'public', table: 'map_tokens', filter: `campaign_id=eq.${campaignId}` }, payload => handlers.token(payload.eventType, token((payload.new || payload.old) as Row))).on('postgres_changes', { event: 'UPDATE', schema: 'public', table: 'personagens', filter: `campaign_id=eq.${campaignId}` }, payload => handlers.character(characterResource(payload.new as Row))).subscribe(handlers.status); }
};
